image: node

stages: 
  - build 
  - deploy

install:
  stage: build
  script:  
    - npm install 
    - npm run build
    - echo 'finish running'
    - npm firebase install
    - firebase deploy --token
  
