image: node

stages: 
  - build 
  - deploy

install:
  stage: build
  script:  
    - npm install 
    - CI=false && npm run build
    - echo 'finish running'
    - npm install firebase
    - firebase deploy --token
  
